from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

if not GetDepend('RT_USING_SERIAL'):
    SrcRemove(src, ['drv_uart.c'])

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
